repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0  # Check for latest version
    hooks:
      - id: pylint
        args: ["*.py", "*/*.py", --disable=import-error]
